### ISSUE TITLE
Case incorrect on Docker image for Kubernetes

### ISSUE THREAD

**Issue by coleca** [AutoSpotting/AutoSpotting#311]
# Github issue #

## Issue type ##

- Bug Report

## Build number #

```text
nightly-f835dc7
```

## Configuration ##

Kubernetes using K8S example

## Environment ##

- us-east-1
- vpc

```yaml
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: autospotting
  namespace: prod
spec:
  schedule: "*/5 * * * *" # run every 5 minutes
  startingDeadlineSeconds: 100 # skip if it hasn't started in this many seconds
  concurrencyPolicy: Forbid # either allow|forbid|replace
  successfulJobsHistoryLimit: 1 # how many completed jobs should be kept
  failedJobsHistoryLimit: 1 # how many failed jobs should be kept
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: autospotting-cron-job
              image: autospotting/autospotting:latest
              # Environment variables for the AutoSpotting pod
              # Feel free to configure them to suit your needs
              env:
                # These hardcoded credentials could be removed if using a secret
                # object or Kube2IAM
                # (patches always welcome if you get this working otherwise)
                - name: ALLOWED_INSTANCE_TYPES
                  value: "*"
                - name: BIDDING_POLICY
                  value: "normal"
                - name: DISALLOWED_INSTANCE_TYPES
                  value: "a1.*,t2.*,t1.*,t3.*,cc2.*,m5.*,c5.*,c5d.*,m5d.*,c3.*,g3.*"
                - name: INSTANCE_TERMINATION_METHOD
                  value: "autoscaling"
                - name: MIN_ON_DEMAND_NUMBER
                  value: "0"
                - name: MIN_ON_DEMAND_PERCENTAGE
                  value: "0.0"
                - name: ON_DEMAND_PRICE_MULTIPLIER
                  value: "1.0"
                - name: REGIONS
                  value: "us-east-1"
                - name: SPOT_PRICE_BUFFER_PERCENTAGE
                  value: "10.0"
```

## Summary ##

Image not found when launching.  Get an ImagePullFailure

## Steps to reproduce ##

Use the current example K8S example file.

## Expected results ##

Launch Autospotting image

## Actual results ##

Couldn't find autospotting image because the case should all be lowercase as it is on Dockerhub.
